### ISSUE TITLE
Objectify parses numbers incorrectly

### ISSUE THREAD

**Issue by FredrikSeidl** [lucasreppewelander/query-string-manager#4]
When parsing the following query string with objectify `?utm_campaign=2020-2` the output becomes this `{ utm_campaign: 2020 }` but it should've been `{ utm_campaign: "2020-2" }`

**Comment by lucasreppewelander** [comment]
waiting for approval by FredrikSeidl

**Comment by FredrikSeidl** [comment]
Solution looks good. Closing issue
